apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-redis
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-redis
  template:
    metadata:
      labels:
        app: immich-redis
    spec:
      containers:
      - name: immich-redis
        image: registry.hub.docker.com/library/redis:6.2-alpine
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: immich-redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: immich-redis